language: C
compiler: gcc
dist: bionic

#branches:
#  only:
#    master
#    /^v\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  hosts:
    - travis.local

  apt:
    packages:

  sonarcloud:
    organization: ${SONARCLOUD_ORGANIZATION}
    token:

jobs:
  include:
    - stage: sonarcloud
      script:
        - git clone ${GITHUB_QUALITY_TESTS} -b ${TRAVIS_BRANCH} quality
        - pushd quality && make sonar-analyze && popd
    - stage: release
      script:
        make clean && make &&
        mkdir -p ${PWD}/release/usr/lib &&
        mkdir -p ${PWD}/release/usr/include/tinysvcmdns &&
        cp libtinysvcmdns.a ${PWD}/release/usr/lib &&
        cp mdnsd.h mdns.h ${PWD}/release/usr/include/tinysvcmdns &&
        pushd ${PWD}/release && tar -czf ../tinysvcmdns-travis.tar.gz . && popd
